const elem = {
  btnList: document.getElementsByClassName("btn"),
  btnGroup: document.getElementById("btn-group"),
  boardCanvas: document.getElementById("board"),
  playerCanvas: document.getElementById("player"),
  html: document.getElementsByTagName("html")[0],
  audio: document.getElementById("audio-controls"),
  mute: document.getElementById("mute"),
  play: document.getElementById("play"),
  imgGroup: document.getElementById("image-group"),
  cardGroup: document.getElementsByClassName("card"),
  btn1: document.getElementById("playBtn"),
  btn2: document.getElementById("continueBtn"),
  page1: document.getElementById("page-1"),
  page2: document.getElementById("page-2"),
  page3: document.getElementById("page-3"),
  easyBtn: document.getElementById("btn-easy"),
  mediumBtn: document.getElementById("btn-medium"),
  hardBtn: document.getElementById("btn-hard"),
  avatar: document.getElementById("avatar"),
  modal: document.querySelector(".modal"),
  modalBtn: document.querySelector(".modal_btn"),
  winningScreen: document.getElementById("winning-screen"),
  winningText: document.getElementById("winning-text"),
  counter: document.getElementById("counter"),
  counterText: document.querySelectorAll("#counter p"),
  stepCounter: document.querySelector("#counter #step span"),
  timeCounter: document.querySelector("#counter #time span")
};

export default elem;
